### ISSUE TITLE
Installing project renames .gitignore to npmignore

### ISSUE THREAD

**Issue by richross** [philliphoff/generator-webtile#1]
Ran the procedures on the readme file to install generate-webtile project.  In creating the first project, I had an error stating that the .gitignore template was missing.  The folder it was searching contained a .npmignote instead.  I checked the contents and they matched the .gitignore that exists in your repo.  I renamed the file locally and was able to generate a webtile project.

**Comment by philliphoff** [comment]
Thanks for the feedback.  It looks like the NPM packaging process renames (!?!) .gitignore files to .npmignore.  I've updated the template files so as to avoid this behavior and updated the package.

**Comment by philliphoff** [comment]
Closed with commit 39d5d05f78d86a9d84da6cd477053993fb7865a2.
